main/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from main import views
from rest_framework_simplejwt import views as jwt_views


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    path('', views.indexView.as_view() ),
    path('search/<str:searchType>/<str:user>/<str:value>', views.searchView.as_view() ),

    path('accounts/<str:type>/<str:value>/<str:token>', views.getView.as_view()),
    path('info/<str:username>', views.getInfoView.as_view()),
    path('user/login/token', jwt_views.TokenObtainPairView.as_view(), name='get_token'),
    path('user/login/token/refresh', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('user/register', views.registerView.as_view() ),

    path('user/register/grossiste/<str:username>/<str:ville>', views.registerGrossisteView.as_view() ),
    path('user/register/revendeur/<str:username>/<str:ville>', views.registerRevendeurView.as_view() ),

    path('article/<int:pk>/<str:token>', views.articleView.as_view() ),


    
]

    

vente_gros_details/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from main.utils import *
# Create your models here.


class Admin(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nom de votre compte", unique=True )
    description = models.TextField(max_length=10000, null=True, blank=True, verbose_name="A propos de moi" )
    phone1 = models.IntegerField(verbose_name="Numéro de téléphone whatsapp")
    phone2 = models.IntegerField(null=True, blank=True, verbose_name="Autre numéro de téléphone (Falcutatif)")
    facebook_link = models.CharField(max_length=500,  default="https://...", null=True, blank=True, verbose_name="Lien page facebook")
    twitter_link = models.CharField(max_length=500, default="https://...", null=True, blank=True,  verbose_name="Lien page twitter")
    instagram_link = models.CharField(max_length=500, default="https://...", null=True,  blank=True, verbose_name="Lien page intsagram")
    youtube_link = models.CharField(max_length=500, default="https://...", null=True,  blank=True, verbose_name="Lien page intsagram")
    
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    
    class Meta:
        verbose_name = "Administration"



class Country(models.Model):
    name = models.CharField(max_length=50, blank=True,  null=True)
    drapeau = models.ImageField(upload_to='flags/', null=True,  blank=True, verbose_name="drapeau")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")

    class Meta:
        verbose_name = "Pay"
        ordering = ['name']

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=50, blank=True,  null=True)
    country = models.ForeignKey(Country, null=True, on_delete = models.PROTECT, verbose_name="Pays")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")

    class Meta:
        verbose_name = "Ville"
        ordering = ['name']

    def __str__(self):
        return self.name

class Quartier(models.Model):
    name = models.CharField(max_length=50, blank=True,  null=True)
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")

    class Meta:
        verbose_name = "Quartier"
        ordering = ['name']

    def __str__(self):
        return self.name


class Big_category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nom de la grande catégorie" )
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    class Meta:
        verbose_name = "Grande Catégorie"

    def __str__(self):
        return self.name


class Categorie(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nom de la catégorie" )
    big_category = models.ForeignKey(Big_category, null=True, on_delete = models.PROTECT, verbose_name="Grande catégorie")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    class Meta:
        verbose_name = "Catégorie"

    def __str__(self):
        return self.name




class Tag(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nom du tag" )
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    class Meta:
        verbose_name = "Tag"

    def __str__(self):
        return self.name


class Grossiste(models.Model):
    user = models.OneToOneField(User, null=True, on_delete = models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Nom de mon compte", unique=True )
    
    description = models.TextField(max_length=10000, null=True, blank=True, verbose_name="A propos de moi" )
    phone1 = models.IntegerField(verbose_name="Numéro de téléphone whatsapp")
    phone2 = models.IntegerField(null=True, blank=True, verbose_name="Autre numéro de téléphone (Falcutatif)")
    country = models.ForeignKey(Country, null=True, on_delete = models.PROTECT, verbose_name="Pays")
    quartier = models.ForeignKey(Quartier,null=True, blank=True, on_delete = models.PROTECT, verbose_name="Quartier")
    categories = models.ManyToManyField(Categorie, null=True, blank=True)
    tags = models.ManyToManyField(Tag, null=True)
    token = models.CharField(max_length=100, verbose_name="Token" )
    facebook_link = models.CharField(max_length=500, default="https://...", null=True, blank=True, verbose_name="Lien page facebook")
    twitter_link = models.CharField(max_length=500, default="https://...", null=True, blank=True,  verbose_name="Lien page twitter")
    instagram_link = models.CharField(max_length=500, default="https://...", null=True,  blank=True, verbose_name="Lien page instagram")
    city = models.ForeignKey(City, on_delete = models.PROTECT, null=True, blank=True, verbose_name="Ville")

    avatar = models.ImageField(upload_to='avatars/',  verbose_name="Avatar")


    pubChoices = [
        ('true', 'true'),
        ('false', 'false'),
    ]
    pub = models.CharField(
        max_length=5,
        choices=pubChoices,
        default='false',
    )
    token = models.CharField(max_length=100, verbose_name="Token" )
    
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    class Meta:
        verbose_name = "Grossiste"
    def __str__(self):
        return self.name + ', '+self.user.username 


class Revendeur(models.Model):
    user = models.OneToOneField(User, null=True, on_delete = models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Nom de votre compte", unique=True )
    description = models.TextField(max_length=10000, null=True, blank=True, verbose_name="A propos de moi" )
    phone1 = models.IntegerField(verbose_name="Numéro de téléphone whatsapp")
    phone2 = models.IntegerField(null=True, blank=True, verbose_name="Autre numéro de téléphone (Falcutatif)")
    country = models.ForeignKey(Country, null=True, on_delete = models.PROTECT, verbose_name="Pays")
    categories = models.ManyToManyField(Categorie,null=True, blank=True)
    quartier = models.ForeignKey(Quartier, null=True, blank=True,  on_delete = models.PROTECT, verbose_name="Quartier")
    grossistes = models.ManyToManyField(Grossiste, null=True, blank=True, verbose_name="Grossistes du Revendeur")
    facebook_link = models.CharField(max_length=500,  default="https://...", null=True, blank=True, verbose_name="Lien page facebook")
    twitter_link = models.CharField(max_length=500, default="https://...", null=True, blank=True,  verbose_name="Lien page twitter")
    instagram_link = models.CharField(max_length=500, default="https://...", null=True,  blank=True, verbose_name="Lien page intsagram")
    avatar = models.ImageField(upload_to='avatars/', verbose_name="Avatar")
    city = models.ForeignKey(City, on_delete = models.PROTECT,  null=True, blank=True, verbose_name="Ville")
    pubChoices = [
        ('true', 'true'),
        ('false', 'false'),
    ]
    pub = models.CharField(
        max_length=5,
        choices=pubChoices,
        default='false',
    )
    token = models.CharField(max_length=100, verbose_name="Token" )
    
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    
    class Meta:
        verbose_name = "Revendeur"
    def __str__(self):
        return self.name + ' '+ self.user.username 

class Article(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nom de l'article", )
    description = models.TextField(max_length=10000, null=True, blank = True, verbose_name="Description de l'article" )
    tags = models.CharField(max_length=100, null=True, blank = True, verbose_name="Tags" )
    categorie = models.ForeignKey(Categorie, null=True, on_delete = models.PROTECT)
    stock = models.PositiveIntegerField(null=True, default=0, blank=True, verbose_name="Stock disponible")
    stock_price = models.PositiveIntegerField(null=True, default=0, blank=True, verbose_name="Prix du Stock (prix en gros)")
    stock_size = models.PositiveIntegerField(null=True, default=0, blank=True, verbose_name="Nombre d'articles par stock")
    image = models.ImageField(upload_to='images/',  verbose_name="Image de l'article")
    image_mini = models.ImageField(upload_to='images_mini/', default=0, null=True, blank=True, verbose_name="Image miniature de l'article")
    grossiste = models.ForeignKey(Grossiste, null=True, blank=True, on_delete = models.PROTECT, verbose_name="Grossiste")
    pubChoices = [
        ('true', 'true'),
        ('false', 'false'),
    ]
    pub = models.CharField(
        max_length=5,
        choices=pubChoices,
        default='false',
    )
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Date de création")
    updated_at = models.DateTimeField(default=timezone.now, verbose_name="Date de supression")
    
    class Meta:
        verbose_name = "Article"

    def __str__(self):
        return self.name

templates/single-product.html
{% extends "base.html" %}
{% block content %}
{% load static %}


	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb" >
	</section>
	<!-- End Banner Area -->

	<!--================Single Product Area =================-->
	<div class="product_image_area" style=" margin:0; margin-top: 30px; padding: 0 ">
		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
					<div class="s_Product_carousel">
						<div class="single-prd-item">
							<img class="img-fluid" src="/media/{{article.image}}"  alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid" src="/media/{{article.image}}"  alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid" src="/media/{{article.image}}"  alt="">
						</div>
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					{% if auth %}
					<div class="row">
						<div class="col-md-6">
							<a href="#" data-toggle="modal" data-target="#editModal" style="font-size:0.9em; width: 100%; color: #222222" class="genric-btn primary radius">
									<span class="">
										<i class="fa fa-edit"></i>
									</span>
									Modifier
							</a>
						</div>
						<div class="col-md-6">
							<a href="#" data-toggle="modal" data-target="#deleteModal" style="font-size:0.9em;  width: 100%"  class="genric-btn danger radius">
								<span class="">
									<i class="fa fa-trash"></i>
								</span>
								Supprimer
							</a>
						</div>
					</div>
					{% endif %}
					<div class="s_product_text" style=" margin:0;  margin-top: 10px; padding: 0 ">
						<h3>{{article.name}}</h3>
						<h2>{{article.stock_price}} FCFA / stock</h2>
						<ul class="list">
							<li><span>Quantitée par stock</span> : {{article.stock_size}} </li>
							<li><span>Stock disponible</span> : {{article.stock}} </li>
							<li><span>Categorie</span> : {{article.categorie}} </li>
						</ul>
						<p>{{article.description}} </p>
						<!--div class="product_count">
							<label for="qty">Quantity:</label>
							<input type="text" name="qty" id="sst" maxlength="12" value="1" title="Quantity:" class="input-text qty">
							<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
							 class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
							<button onclick="var result = document.getElementById('sst'); var sst = result.value; if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;return false;"
							 class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
						</div-->
				
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->

										
	<!--================Product Description Area =================-->
	<section class="product_description_area" style="margin:0; margin-bottom: 30px;margin-top: 10px;  padding: 0 ">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					{% if auth %}
					<a href="/accounts/grossiste/{{article.grossiste.name}}/{{token}}"  id="homeLink" style="font-size:0.9em; width: 100% ; background: #ff6c00"  class="genric-btn primary radius">
						<span class="">
							<i class="fa fa-home"></i>
						</span>
						Page du Grossiste
					</a>
					{% else %}
					<a href="/accounts/grossiste/{{article.grossiste.name}}/a" style="font-size:0.9em; width: 100% ; background: #ff6c00"  class="genric-btn primary radius">
						<span class="">
							<i class="fa fa-home"></i>
						</span>
						Page du Grossiste
					</a> 
					{% endif %}
					
				</div>
				<div class="col-md-3">
					<a href="https://api.whatsapp.com/send?phone={{article.grossiste.phone1}}" style="font-size:0.9em; width: 100% ;padding: 10px"  class="btn btn-success radius">
						<span class="">
							<i class="fa fa-whatsapp"></i>
							<i class="fa fa-phone"></i>
						</span>
						whatsapp
					</a>
				</div>
				<div class="col-md-3">
					<a href="{{article.grossiste.facebook_link}}" style="font-size:0.9em;  width: 100%"  class="genric-btn info radius">
						<span class="">
							<i class="fa fa-facebook"></i>
						</span>
						Page facebook
					</a>
				</div>
				<div class="col-md-3">
					<a href="{{article.grossiste.instagram_link}}" style="font-size:0.9em; padding: 10px; width: 100%" class="btn btn-warning radius">
						<span class="">
							<i class="fa fa-instagram"></i>
						</span>
						Page Instagram
					</a>
				</div>
			</div>
			
			
		</div>
	</section>
	<!--================End Product Description Area =================-->

	<!-- Start related-product Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>A propos de nous</h6>
						<p>
							Nous formons un grand marché et un grand réseaux de grossistes et de revendeurs. 
						</p>
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Suivez nous </h6>
						<p>sur les réseaux sociaux et ne ratez rien des nouveautés et des bonnes affaires</p>
						<div class="footer-social d-flex align-items-center">
							<a href="https://api.whatsapp.com/send?phone={{admin.phone1}}" ><i class="fa fa-whatsapp"></i></a>
							<a href="{{admin.facebook_link}}" ><i class="fa fa-instagram"></i></a>
							<a href="{{admin.instagram_link}}" ><i class="fa fa-facebook"></i></a>
							<a href="{{admin.youtube_link}}" ><i class="fa fa-youtube"></i></a>
							<a href="{{admin.twitter_link}}" ><i class="fa fa-twitter"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved  | Website  made by Horace FAYOMI and template with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="{% static 'https://colorlib.com' %}"  target="_blank">Colorlib</a> 
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
			</div>
		</div>
	</footer>
<div id="container-floating" >
    <div id="floating-button">
    	<div class="row">
    		<a href="{{admin.facebook_link}}" ><i class="fa fa-facebook"></i></a>
    	</div>
    	<div class="row">
    		<a href="https://api.whatsapp.com/send?phone={{admin.phone1}}" ><i class="fa fa-whatsapp" style="color: green"></i></a>
    	</div>
    	<div class="row">
    		<a href="{{admin.instagram_link}}" ><i class="fa fa-instagram" style="color: #6503a8"></i></a>
    	</div>
    	<div class="row">
    		<a href="{{admin.twitter_link}}" ><i class="fa fa-twitter"></i></a>
    	</div>
    	<div class="row">
    		<a href="#category"  style="color: #222"><i class="fa fa-arrow-up"></i></a>
    	</div>
    </div>
</div>

	
	<div class="modal fade " id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	          <img src="{% static 'img/logo.png' %}" style="max-height: 16px; max-width: 100px "  alt="" class="">
          <h5 class="modal-title " id="exampleModalLabel" style="color: #575d79">&nbsp|&nbsp Modifier un article</h5>   
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>

	      <div class="modal-body" style="padding-left: 10%; padding-right: 10%; padding-bottom: 5%;">
	        <form id="updateArticleForm" action="/article/{{pk}}/{{token}}"   >

			            {% csrf_token %}

			            {{ updateArticleForm.as_p }}
			    <br>
				<button type="submit" style="color: #000; font-size: 1em" class="btn  btn-block  genric-btn primary" > Modifier </button> 
			</form>
	      </div>
	      
	    </div>
	  </div>
	</div>

	<div class="modal fade " id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	          <img src="{% static 'img/logo.png' %}" style="max-height: 50px; max-width: 70px "  alt="" class="img-fluid">
	          <h5 class="modal-title " id="exampleModalLabel" style="color: #222222">&nbsp Modification</h5>  
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>

	      <div class="modal-body" style="padding-left: 10%; padding-right: 10%; padding-bottom: 5%;">
	      	Voulez vous vraiment supprimer ?

	        {% if auth %}
					<div class="row" style="margin-top: 10px">
						<div class="col-md-6">
							<a href="#" data-dismiss="modal" aria-label="Close" style="font-size:0.9em;  width: 100%"  class="genric-btn primary radius">
								Non
							</a>
						</div>
						<div class="col-md-6">
							<a href="/article/{{pk}}/{{token}}" id="delete" style="font-size:0.9em;  width: 100%; " class="genric-btn danger radius">
									Oui
							</a>
						</div>
					</div>
			{% endif %}
	      </div>
	      
	    </div>
	  </div>
	</div>
	<!-- End footer Area -->

	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}" ></script>
	<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js' %}"  integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}" ></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}" ></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}" ></script>
	<script src="{% static 'js/jquery.sticky.js' %}" ></script>
	<script src="{% static 'js/nouislider.min.js' %}" ></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}" ></script>
	<script src="{% static 'js/owl.carousel.min.js' %}" ></script>
	<!--gmaps Js-->
	<script src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE' %}" ></script>
	<script src="{% static 'js/gmaps.min.js' %}" ></script>
	<script src="{% static 'js/main.js' %}" ></script>
	<script type="text/javascript">
		$(function(){
			$('.img-fluid').css('min-height','300px')
			$('.img-fluid').css('max-height','700px')
			$('.owl-stage-outer').css('box-shadow','0px 4px 5px 0px rgba(0, 0, 0, 0.2)').bind('mouseenter',function(){
				$(this).css('box-shadow','0px 7px 8px 0px #828bb3')
			}).bind('mouseleave',function(){
				$(this).css('box-shadow','0px 4px 5px 0px rgba(0, 0, 0, 0.2)')
			}) 

			$('#editModal .register').css('display','none').css('visibility','invisible')
			//$('#editModal #id_token').parent().css('display','none').css('visibility','invisible')
			$('#editModal input, #editModal select, #editModal textarea').css('width','100%')
			//nice-select
			$('#editModal label').wrap('<div class="d-flex flex-wrap align-items-left justify-content-left" ></div>')
			$('#editModal p').after('<br>')
			$('#id_grossiste').parent().css('display','none').css('visibility','invisible')
			
			$('#delete').click(function(e){
				e.preventDefault();
				$.ajax({
			        url: $(this).attr('href'),
			        type: 'DELETE',
			        success: function (data) {
			        	console.log(data)
			        	window.location.href = $('#homeLink').attr('href')
			        },
			    });
			})

			$("#updateArticleForm").submit(function(e) {
			    e.preventDefault();
			    var formData = new FormData(this);   
			    $.ajax({
			        url: $(this).attr('action'),
			        type: 'POST',
			        data: formData,
			        success: function (data) {
			        	console.log(data)
			        	if( data.status == 'success'){
			        		console.log(data)
			        		window.location.href = window.location.href 
			        	}
			        	else{
			        		$('#updateArticleForm .errorMessage').remove()
			            	$('#updateArticleForm button').before('<div class="alert alert-danger errorMessage"  style="padding: 5px" role="alert">'+  data.status +'!</div>')
			        	}
			        	
			        },
			        cache: false,
			        contentType: false,
			        processData: false,
			        enctype: 'multipart/form-data',
			    });
			});
		})
	</script>

{% endblock %}